/*
 * regions.js
 * @author Sebastian Arana
 */

/*  */
const regions = {
	"hokkaido":   "hokkaido-tohoku",
	"aomori":     "hokkaido-tohoku",
	"iwate":      "hokkaido-tohoku",
	"miyagi":     "hokkaido-tohoku",
	"akita":      "hokkaido-tohoku",
	"yamagata":   "hokkaido-tohoku",
	"fukushima":  "hokkaido-tohoku",
	"ibaraki":    "kanto",
	"tochigi":    "kanto",
	"gunma":      "kanto",
	"saitama":    "kanto",
	"chiba":      "kanto",
	"tokyo":      "kanto",
	"kanagawa":   "kanto",
	"niigata":    "chubu",
	"toyama":     "chubu",
	"ishikawa":   "chubu",
	"fukui":      "chubu",
	"yamanashi":  "chubu",
	"nagano":     "chubu",
	"gifu":       "chubu",
	"shizuoka":   "chubu",
	"aichi":      "chubu",
	"mie":        "kinki",
	"shiga":      "kinki",
	"kyoto":      "kinki",
	"osaka":      "kinki",
	"hyogo":      "kinki",
	"nara":       "kinki",
	"wakayama":   "kinki",
	"tottori":    "chugoku-shikoku",
	"shimane":    "chugoku-shikoku",
	"okayama":    "chugoku-shikoku",
	"hiroshima":  "chugoku-shikoku",
	"yamaguchi":  "chugoku-shikoku",
	"tokushima":  "chugoku-shikoku",
	"kagawa":     "chugoku-shikoku",
	"ehime":      "chugoku-shikoku",
	"kochi":      "chugoku-shikoku",
	"fukuoka":    "kyushu-okinawa",
	"saga":       "kyushu-okinawa",
	"nagasaki":   "kyushu-okinawa",
	"kumamoto":   "kyushu-okinawa",
	"oita":       "kyushu-okinawa",
	"miyazaki":   "kyushu-okinawa",
	"kagoshima":  "kyushu-okinawa",
	"okinawa":    "kyushu-okinawa",
};
