const regions = {
	"Hokkaido": "Hokkaido-Tohoku",
	"Aomori": "Hokkaido-Tohoku",
	"Iwate": "Hokkaido-Tohoku",
	"Miyagi": "Hokkaido-Tohoku",
	"Akita": "Hokkaido-Tohoku",
	"Fukushima": "Hokkaido-Tohoku",
	"Yamagata": "Hokkaido-Tohoku",

	"Tochigi": "Kanto",
	"Saitama": "Kanto",
 	"Chiba": "Kanto",
	"Tokyo": "Kanto",
	"Kanagawa": "Kanto",
	"Ibaraki": "Kanto",
	"Gunma": "Kanto",

	"Niigata": "Chubu",
	"Toyama": "Chubu",
	"Ishikawa": "Chubu",
	"Fukui": "Chubu",
	"Gifu": "Chubu",
	"Shizuoka": "Chubu",
	"Aichi": "Chubu",
	"Yamanashi": "Chubu",
	"Nagano": "Chubu",

	"Mie": "Kinki",
	"Shiga": "Kinki",
	"Kyoto": "Kinki",
	"Osaka": "Kinki",
	"Hyogo": "Kinki",
	"Nara": "Kinki",
	"Wakayama": "Kinki",

	"Tottori": "Chugoku-Shikoku",
	"Shimane": "Chugoku-Shikoku",
	"Okayama": "Chugoku-Shikoku",
	"Yamaguchi": "Chugoku-Shikoku",
	"Tokushima": "Chugoku-Shikoku",
	"Kagawa": "Chugoku-Shikoku",
	"Ehime": "Chugoku-Shikoku",
	"Hiroshima": "Chugoku-Shikoku",
	"Kochi": "Chugoku-Shikoku",

	"Fukuoka": "Kyushu-Okinawa",
	"Saga": "Kyushu-Okinawa",
	"Nagasaki": "Kyushu-Okinawa",
	"Miyazaki": "Kyushu-Okinawa",
	"Kagoshima": "Kyushu-Okinawa",
	"Okinawa": "Kyushu-Okinawa",
	"Kumamoto": "Kyushu-Okinawa",
	"Oita": "Kyushu-Okinawa",
};
